name: Docs

on:
  push:
    branches:
      - main
      - testing
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - testing

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install dependencies
        run: julia --project=docs -e 'import Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.precompile()'

      - name: Run test suite
        run: julia --project=. test/runtest.jl

  build:
    name: Build & deploy docs
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install dependencies for docs
        run: julia --project=docs -e 'import Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.precompile()'

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY  }}
        run: julia --project=docs docs/make.jl